// https://searchfox.org/mozilla-central/rev/7c20ad925005fbad7b8e08813115f1ec7fa1c248/netwerk/mime/nsMimeTypes.h
module.exports = {
    browser: 'Firefox',
    mimeTypes: [
       { type: 'application/applefile' },
       { type: 'application/mac-binhex40' },
       { type: 'application/x-macbinary' },
       { type: 'application/x-compress' },
       { type: 'application/compress' },
       { type: 'application/x-fortezza-ckl' },
       { type: 'application/x-fortezza-krl' },
       { type: 'application/x-gzip' },
       { type: 'application/gzip' },
       { type: 'application/x-gunzip' },
       { type: 'application/brotli' },
       { type: 'application/zip' },
       { type: 'application/http-index-format' },
       { type: 'application/ecmascript' },
       { type: 'application/javascript' },
       { type: 'application/x-javascript' },
       { type: 'application/json' },
       { type: 'application/x-netscape-revocation' },
       { type: 'application/x-ns-proxy-autoconfig' },
       { type: 'application/x-javascript-config' },
       { type: 'application/octet-stream' },
       { type: 'application/pgp' },
       { type: 'application/x-pgp-message' },
       { type: 'application/postscript' },
       { type: 'application/pdf' },
       { type: 'application/pre-encrypted' },
       { type: 'application/rdf+xml' },
       { type: 'application/x-uuencode' },
       { type: 'application/x-uue' },
       { type: 'application/uuencode' },
       { type: 'application/uue' },
       { type: 'application/x-x509-ca-cert' },
       { type: 'application/x-x509-server-cert' },
       { type: 'application/x-x509-email-cert' },
       { type: 'application/x-x509-user-cert' },
       { type: 'application/x-pkcs7-crl' },
       { type: 'application/x-pkcs7-mime' },
       { type: 'application/pkcs7-mime' },
       { type: 'application/x-pkcs7-signature' },
       { type: 'application/pkcs7-signature' },
       { type: 'application/x-www-form-urlencoded' },
       { type: 'application/oleobject' },
       { type: 'application/x-oleobject' },
       { type: 'application/java-archive' },
       { type: 'application/marimba' },
       { type: 'application/manifest+json' },
       { type: 'application/x-marimba' },
       { type: 'application/x-xpinstall' },
       { type: 'application/xml' },
       { type: 'application/xhtml+xml' },
       { type: 'application/xslt+xml' },
       { type: 'application/mathml+xml' },
       { type: 'application/rdf+xml' },
       { type: 'application/vnd.wap.xhtml+xml' },
       { type: 'application/package' },
       { type: 'application/javascript-binast' },
       { type: 'application/wasm' },

       { type: 'audio/basic' },
       { type: 'audio/ogg' },
       { type: 'audio/x-wav' },
       { type: 'audio/webm' },
       { type: 'audio/mpeg' },
       { type: 'audio/mp4' },
       { type: 'audio/amr' },
       { type: 'audio/flac' },
       { type: 'audio/3gpp' },
       { type: 'audio/3gpp2' },
       { type: 'audio/x-midi' },
       { type: 'audio/x-matroska' },
       { type: 'audio/aac' },

       { type: 'binary/octet-stream' },

       { type: 'image/gif' },
       { type: 'image/jpeg' },
       { type: 'image/jpg' },
       { type: 'image/pjpeg' },
       { type: 'image/png' },
       { type: 'image/apng' },
       { type: 'image/x-png' },
       { type: 'image/x-portable-pixmap' },
       { type: 'image/x-xbitmap' },
       { type: 'image/x-xbm' },
       { type: 'image/xbm' },
       { type: 'image/x-jg' },
       { type: 'image/tiff' },
       { type: 'image/bmp' },
       { type: 'image/x-ms-bmp' },
        // This is used internally to represent Windows clipboard BMPs which remove
        // part of the header.
       { type: 'image/x-ms-clipboard-bmp' },
       { type: 'image/x-icon' },
       { type: 'image/vnd.microsoft.icon' },
       { type: 'image/icon' },
       { type: 'video/x-mng' },
       { type: 'image/x-jng' },
       { type: 'image/svg+xml' },
       { type: 'image/webp' },

       { type: 'message/external-body' },
       { type: 'message/news' },
       { type: 'message/rfc822' },

       { type: 'multipart/alternative' },
       { type: 'multipart/appledouble' },
       { type: 'multipart/digest' },
       { type: 'multipart/form-data' },
       { type: 'multipart/header-set' },
       { type: 'multipart/mixed' },
       { type: 'multipart/parallel' },
       { type: 'multipart/signed' },
       { type: 'multipart/related' },
       { type: 'multipart/x-mixed-replace' },
       { type: 'multipart/byteranges' },

       { type: 'x-sun-attachment' },

       { type: 'text/enriched' },
       { type: 'text/calendar' },
       { type: 'text/html' },
       { type: 'text/mdl' },
       { type: 'text/plain' },
       { type: 'text/richtext' },
       { type: 'text/vcard' },
       { type: 'text/css' },
       { type: 'text/jsss' },
       { type: 'text/json' },
       { type: 'text/xml' },
       { type: 'text/rdf' },
       { type: 'text/vtt' },
       { type: 'application/vnd.mozilla.xul+xml' },
       { type: 'text/ecmascript' },
       { type: 'text/javascript' },
       { type: 'text/xsl' },
       { type: 'text/event-stream' },
       { type: 'text/cache-manifest' },

       { type: 'video/mpeg' },
       { type: 'video/mp4' },
       { type: 'video/quicktime' },
       { type: 'video/x-raw-yuv' },
       { type: 'video/ogg' },
       { type: 'video/webm' },
       { type: 'video/3gpp' },
       { type: 'video/3gpp2' },
       { type: 'video/mp2t' },
       { type: 'video/avi' },
       { type: 'video/x-matroska' },
       { type: 'application/ogg' }
    ]
};
